# Generated by Django 6.0 on 2025-12-17 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to this sprint', related_name='sprint_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
