# Generated by Django 5.2.9 on 2025-12-17 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0002_sprint_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='members',
        ),
        migrations.AddField(
            model_name='sprint',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='User assigned to work on this sprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sprints', to=settings.AUTH_USER_MODEL),
        ),
    ]
