# Generated by Django 6.0 on 2025-12-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('can_create_projects', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_create_sprints', models.BooleanField(default=False)),
                ('can_start_sprints', models.BooleanField(default=False)),
                ('can_assign_tasks', models.BooleanField(default=False)),
                ('can_update_any_task', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Permission Profile',
                'verbose_name_plural': 'Group Permission Profiles',
            },
        ),
    ]
