# Generated by Django 4.2.7 on 2025-11-21 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DEVELOPER", "Developer"),
                            ("TESTER", "Tester"),
                            ("DESIGNER", "Designer"),
                            ("ANALYST", "Analyst"),
                            ("DEVOPS", "DevOps"),
                        ],
                        default="DEVELOPER",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member_roles",
                        to="tasks.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
                "unique_together": {("team", "user")},
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PROJECT_PROGRESS", "Project Progress"),
                            ("SPRINT_METRICS", "Sprint Metrics"),
                            ("EMPLOYEE_PERFORMANCE", "Employee Performance"),
                            ("TEAM_VELOCITY", "Team Velocity"),
                            ("TASK_COMPLETION", "Task Completion"),
                            ("PRODUCTIVITY_SUMMARY", "Productivity Summary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField()),
                ("format", models.CharField(default="PDF", max_length=20)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(fields=["type"], name="reports_type_4f55c9_idx"),
                    models.Index(
                        fields=["generated_at"], name="reports_generat_a38578_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_tasks", models.IntegerField(default=0)),
                ("completed_tasks", models.IntegerField(default=0)),
                ("in_progress_tasks", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("velocity", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="tasks.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="tasks.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["project", "date"], name="analytics_project_a715e7_idx"
                    ),
                    models.Index(
                        fields=["sprint", "date"], name="analytics_sprint__a12a53_idx"
                    ),
                ],
            },
        ),
    ]
